//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4H_Website.C4H_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceType", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class ServiceType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.ServiceType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.ServiceType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(C4H_Website.C4H_Service.DonorProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(C4H_Website.C4H_Service.CharityProfile))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.UserRole RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.UserRole Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonorProfile", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class DonorProfile : C4H_Website.C4H_Service.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BirthYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.UserGender GenderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BirthYear {
            get {
                return this.BirthYearField;
            }
            set {
                if ((this.BirthYearField.Equals(value) != true)) {
                    this.BirthYearField = value;
                    this.RaisePropertyChanged("BirthYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.UserGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharityProfile", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class CharityProfile : C4H_Website.C4H_Service.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.CharityCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.CharityActivityCountry[] CountriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.CharityDesignation DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private C4H_Website.C4H_Service.CharityProgram[] ProgramsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.CharityCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.CharityActivityCountry[] Countries {
            get {
                return this.CountriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CountriesField, value) != true)) {
                    this.CountriesField = value;
                    this.RaisePropertyChanged("Countries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.CharityDesignation Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public C4H_Website.C4H_Service.CharityProgram[] Programs {
            get {
                return this.ProgramsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramsField, value) != true)) {
                    this.ProgramsField = value;
                    this.RaisePropertyChanged("Programs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNumber {
            get {
                return this.RegNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNumberField, value) != true)) {
                    this.RegNumberField = value;
                    this.RaisePropertyChanged("RegNumber");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    public enum UserRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Government = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Charity = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Donor = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGender", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    public enum UserGender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharityCategory", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class CharityCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharityDesignation", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class CharityDesignation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharityActivityCountry", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class CharityActivityCountry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharityProgram", Namespace="http://schemas.datacontract.org/2004/07/C4H_Webservice.Structure")]
    [System.SerializableAttribute()]
    public partial class CharityProgram : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Service", ConfigurationName="C4H_Service.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetServiceTypes", ReplyAction="http://tempuri.org/Service/GetServiceTypesResponse")]
        C4H_Website.C4H_Service.ServiceType[] GetServiceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetServices", ReplyAction="http://tempuri.org/Service/GetServicesResponse")]
        C4H_Website.C4H_Service.Service[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetServicesForSpecificType", ReplyAction="http://tempuri.org/Service/GetServicesForSpecificTypeResponse")]
        C4H_Website.C4H_Service.Service[] GetServicesForSpecificType(int ServiceTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetUserWatchlist", ReplyAction="http://tempuri.org/Service/GetUserWatchlistResponse")]
        C4H_Website.C4H_Service.User[] GetUserWatchlist(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/AddToUserWatchList", ReplyAction="http://tempuri.org/Service/AddToUserWatchListResponse")]
        bool AddToUserWatchList(int UserID, int FollowedUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/RemoveFromUserWatchList", ReplyAction="http://tempuri.org/Service/RemoveFromUserWatchListResponse")]
        bool RemoveFromUserWatchList(int UserID, int FollowedUserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetUserServices", ReplyAction="http://tempuri.org/Service/GetUserServicesResponse")]
        C4H_Website.C4H_Service.Service[] GetUserServices(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/AddToUserServicesList", ReplyAction="http://tempuri.org/Service/AddToUserServicesListResponse")]
        bool AddToUserServicesList(int UserID, int ServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/RemoveromUserServicesList", ReplyAction="http://tempuri.org/Service/RemoveromUserServicesListResponse")]
        bool RemoveromUserServicesList(int UserID, int ServiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetCharityDesignations", ReplyAction="http://tempuri.org/Service/GetCharityDesignationsResponse")]
        C4H_Website.C4H_Service.CharityDesignation[] GetCharityDesignations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetCharityCategories", ReplyAction="http://tempuri.org/Service/GetCharityCategoriesResponse")]
        C4H_Website.C4H_Service.CharityCategory[] GetCharityCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/CreateCharityProfile", ReplyAction="http://tempuri.org/Service/CreateCharityProfileResponse")]
        C4H_Website.C4H_Service.CharityProfile CreateCharityProfile(string UserName, string Password, string FullName, string City, string Province, string PostalCode, string Address1, string Address2, string Phone, string Website, string Email, string RegNumber, int CatetgoryID, int DesignationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetCharityProfileByUserID", ReplyAction="http://tempuri.org/Service/GetCharityProfileByUserIDResponse")]
        C4H_Website.C4H_Service.CharityProfile GetCharityProfileByUserID(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetCharityProfileByUsername", ReplyAction="http://tempuri.org/Service/GetCharityProfileByUsernameResponse")]
        C4H_Website.C4H_Service.CharityProfile GetCharityProfileByUsername(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/CreateDonorProfile", ReplyAction="http://tempuri.org/Service/CreateDonorProfileResponse")]
        C4H_Website.C4H_Service.DonorProfile CreateDonorProfile(string UserName, string Password, string FullName, string City, string Province, string PostalCode, string Address1, string Address2, string Phone, string Website, string Email, C4H_Website.C4H_Service.UserGender Gender, int BirthYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/GetDonorProfileByUsername", ReplyAction="http://tempuri.org/Service/GetDonorProfileByUsernameResponse")]
        C4H_Website.C4H_Service.DonorProfile GetDonorProfileByUsername(string UserName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/SearchCharitiesByQueryPageByPage", ReplyAction="http://tempuri.org/Service/SearchCharitiesByQueryPageByPageResponse")]
        C4H_Website.C4H_Service.CharityProfile[] SearchCharitiesByQueryPageByPage(out int TotalRows, out System.Collections.Generic.Dictionary<string, int> Statistics, out System.Collections.Generic.Dictionary<C4H_Website.C4H_Service.CharityDesignation, int> DesignationStatistics, string Query, string Province, bool LooseSearch, int PageNumber, int RowsPerPageCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service/SearchCharitiesByQuery", ReplyAction="http://tempuri.org/Service/SearchCharitiesByQueryResponse")]
        C4H_Website.C4H_Service.CharityProfile[] SearchCharitiesByQuery(string Query, string Province, bool LooseSearch);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : C4H_Website.C4H_Service.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<C4H_Website.C4H_Service.Service1>, C4H_Website.C4H_Service.Service1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public C4H_Website.C4H_Service.ServiceType[] GetServiceTypes() {
            return base.Channel.GetServiceTypes();
        }
        
        public C4H_Website.C4H_Service.Service[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public C4H_Website.C4H_Service.Service[] GetServicesForSpecificType(int ServiceTypeID) {
            return base.Channel.GetServicesForSpecificType(ServiceTypeID);
        }
        
        public C4H_Website.C4H_Service.User[] GetUserWatchlist(int UserID) {
            return base.Channel.GetUserWatchlist(UserID);
        }
        
        public bool AddToUserWatchList(int UserID, int FollowedUserID) {
            return base.Channel.AddToUserWatchList(UserID, FollowedUserID);
        }
        
        public bool RemoveFromUserWatchList(int UserID, int FollowedUserID) {
            return base.Channel.RemoveFromUserWatchList(UserID, FollowedUserID);
        }
        
        public C4H_Website.C4H_Service.Service[] GetUserServices(int UserID) {
            return base.Channel.GetUserServices(UserID);
        }
        
        public bool AddToUserServicesList(int UserID, int ServiceID) {
            return base.Channel.AddToUserServicesList(UserID, ServiceID);
        }
        
        public bool RemoveromUserServicesList(int UserID, int ServiceID) {
            return base.Channel.RemoveromUserServicesList(UserID, ServiceID);
        }
        
        public C4H_Website.C4H_Service.CharityDesignation[] GetCharityDesignations() {
            return base.Channel.GetCharityDesignations();
        }
        
        public C4H_Website.C4H_Service.CharityCategory[] GetCharityCategories() {
            return base.Channel.GetCharityCategories();
        }
        
        public C4H_Website.C4H_Service.CharityProfile CreateCharityProfile(string UserName, string Password, string FullName, string City, string Province, string PostalCode, string Address1, string Address2, string Phone, string Website, string Email, string RegNumber, int CatetgoryID, int DesignationID) {
            return base.Channel.CreateCharityProfile(UserName, Password, FullName, City, Province, PostalCode, Address1, Address2, Phone, Website, Email, RegNumber, CatetgoryID, DesignationID);
        }
        
        public C4H_Website.C4H_Service.CharityProfile GetCharityProfileByUserID(int UserID) {
            return base.Channel.GetCharityProfileByUserID(UserID);
        }
        
        public C4H_Website.C4H_Service.CharityProfile GetCharityProfileByUsername(string UserName) {
            return base.Channel.GetCharityProfileByUsername(UserName);
        }
        
        public C4H_Website.C4H_Service.DonorProfile CreateDonorProfile(string UserName, string Password, string FullName, string City, string Province, string PostalCode, string Address1, string Address2, string Phone, string Website, string Email, C4H_Website.C4H_Service.UserGender Gender, int BirthYear) {
            return base.Channel.CreateDonorProfile(UserName, Password, FullName, City, Province, PostalCode, Address1, Address2, Phone, Website, Email, Gender, BirthYear);
        }
        
        public C4H_Website.C4H_Service.DonorProfile GetDonorProfileByUsername(string UserName) {
            return base.Channel.GetDonorProfileByUsername(UserName);
        }
        
        public C4H_Website.C4H_Service.CharityProfile[] SearchCharitiesByQueryPageByPage(out int TotalRows, out System.Collections.Generic.Dictionary<string, int> Statistics, out System.Collections.Generic.Dictionary<C4H_Website.C4H_Service.CharityDesignation, int> DesignationStatistics, string Query, string Province, bool LooseSearch, int PageNumber, int RowsPerPageCount) {
            return base.Channel.SearchCharitiesByQueryPageByPage(out TotalRows, out Statistics, out DesignationStatistics, Query, Province, LooseSearch, PageNumber, RowsPerPageCount);
        }
        
        public C4H_Website.C4H_Service.CharityProfile[] SearchCharitiesByQuery(string Query, string Province, bool LooseSearch) {
            return base.Channel.SearchCharitiesByQuery(Query, Province, LooseSearch);
        }
    }
}
